# Generated by Django 3.2.8 on 2021-11-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinder_rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.URLField()),
                ('title', models.TextField()),
                ('director', models.TextField()),
                ('genre', models.TextField()),
                ('IMDB_Rating', models.FloatField()),
                ('cast', models.TextField()),
                ('country', models.TextField()),
                ('description', models.TextField()),
                ('release_year', models.IntegerField()),
                ('duration', models.TextField()),
            ],
        ),
    ]
