# Generated by Django 3.2.8 on 2021-11-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinder_rest_api', '0002_maindb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainDb',
            new_name='Movies',
        ),
    ]
